version: '3'
services:
  test:
    build: .
    command: go test -v

  release:
    build: .
    command: .buildkite/scripts/docker_release.sh
    environment:
      - GITHUB_TOKEN
      - RELEASE_VERSION
