version: '2'
services:
  bolt:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'sh -c "while sleep 1; do :; done"'
    volumes:
      - 'bolt-sync:/go/src/app:rw'
    networks:
      - default
volumes:
  bolt-sync:
    external: true
