version: '3'
services:
  bolt:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "while sleep 1; do :; done"
    volumes:
      - bolt-sync:/usr/src/app:rw
    networks:
      - default

volumes:
  bolt-sync:
    external: true
